services:
  - type: web
    name: chamados-flask
    env: python
    plan: free
    region: oregon
    runtime: python
    buildCommand: ""
    startCommand: gunicorn wsgi:app
    buildFilter:
      paths:
        - "**/*.py"
        - "**/requirements.txt"
        - ".render.yaml"
