# render.yaml
services:
  - type: web
    name: sistema-chamados-nicopel
    env: python
    plan: free 
    region: oregon 
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --worker-class eventlet -w 1 wsgi:app"
    buildFilter:
      paths:
        - "app/**"
        - "migrations/**"
        - "requirements.txt"
        - "wsgi.py"