services:
  - type: web
    name: chamados-flask
    env: python
    plan: free
    region: oregon
    runtime: python
    buildCommand: "pip install -r requirements.txt && rm -rf /opt/render/.cache/pip"
    startCommand: gunicorn --worker-class eventlet -w 1 wsgi:ap
    buildFilter:
      paths:
        - "**/*.py"
        - "**/requirements.txt"
        - ".render.yaml"
