# .render.yaml
services:
  - type: web
    name: sistema-chamados-nicopel
    env: python
    plan: starter # Recomendo o plano 'starter' para evitar que o serviço durma
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    # ✅ CORREÇÃO: O comando agora executa nosso script 'run.py'
    startCommand: "python run.py"
    buildFilter:
      paths:
        - "app/**"
        - "migrations/**"
        - "requirements.txt"
        - "run.py" # Adiciona o novo arquivo ao filtro