services:
  - type: web
    name: nicopel-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ia_server:app
    envVars:
      - key: key
        sync: false
      - key: FLASK_ENV
        value: production
    disk:
      name: data
      mountPath: /data
      sizeGB: 1