# render.yaml

services:
  # --- SERVIÇO 1: O SISTEMA DE CHAMADOS PRINCIPAL ---
  - type: web
    name: sistema-chamados
    env: python
    # O plano 'Starter' é recomendado para evitar que o serviço durma e tenha mais RAM
    plan: starter 
    region: oregon
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_APP
        value: run:app 
      # Adicione suas chaves aqui no painel da Render
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: meubancochamados # SUBSTITUA pelo nome do seu DB na Render
          property: connectionString

    buildCommand: "pip install -r requirements.txt"
    
    # Executa a migração do banco de dados antes de iniciar o servidor
    preDeployCommand: "flask db upgrade"

    # Inicia o servidor do sistema de chamados
    startCommand: "python run.py"
