# render.yaml (para o serviço de IA)
services:
  - type: web
    name: ia-chatbot-nicopel
    env: python
    # O plano gratuito pode não ter RAM suficiente.
    # Considere o plano "Starter" ou superior para rodar o modelo.
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
  
    # ✅ CORREÇÃO: Comando ajustado para o novo nome do arquivo.
    startCommand: "gunicorn run:app --timeout 120"
    startCommand: "flask db upgrade && python run.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      # Adicione sua chave Gemini aqui no painel da Render
      - key: key
        sync: false