# render.yaml - Blueprint para se conectar a um banco de dados externo (Neon.tech)

services:
  # --- SERVIÇO 1: O SISTEMA DE CHAMADOS PRINCIPAL ---
  - type: web
    name: sistema-chamados
    env: python
    plan: free 
    region: oregon
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_APP
        value: run:app 
      - key: PYTHONUNBUFFERED
        value: "1"
      # ✅ CORREÇÃO: A URL do banco agora é uma variável secreta.
      # Você irá colar a string de conexão do Neon diretamente no painel da Render.
      - key: DATABASE_URL
        sync: false
      # Adicione suas outras chaves (SECRET_KEY, GEMINI_API_KEY) no painel da Render.

    buildCommand: "pip install -r requirements.txt"
    preDeployCommand: "flask db upgrade"
    startCommand: "python run.py"

  # --- SERVIÇO 2: A IA DO CHATBOT ---
  - type: web
    name: ia-chatbot
    env: python
    plan: free
    region: oregon

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: key
        sync: false

    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn ia_server:app --timeout 120"