services:
  - type: web
    name: nicopel-chatbot
    env: python
    # ✅ MELHORIA: O plano 'Starter' é o mínimo recomendado para um serviço de IA.
    # Ele não "dorme" e tem mais memória, garantindo que sua IA responda rapidamente.
    plan: free
    region: oregon

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      # ✅ CORREÇÃO: Nome da variável corrigido para corresponder ao código.
      # O valor deve ser colado no painel da Render, não aqui.
      - key: key
        sync: false
      # ✅ MELHORIA: A variável PORT é injetada automaticamente pela Render.
      # Não é necessário defini-la aqui.
      - key: PYTHONUNBUFFERED
        value: "1"

    # Comando para instalar as dependências
    buildCommand: "pip install -r requirements.txt"
    
    # Comando para iniciar o servidor Gunicorn de forma robusta
    startCommand: "gunicorn --workers 1 --threads 4 --timeout 120 ia_server:app"