# render.yaml - Blueprint para se conectar a um banco de dados externo (Neon.tech)

services:
  # --- SERVIÇO 1: O SISTEMA DE CHAMADOS PRINCIPAL ---
  - type: web
    name: sistema-chamados
    env: python
    plan: free 
    region: oregon
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_APP
        value: run:app 
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DATABASE_URL
        sync: false
      - key: key
        sync: false

    buildCommand: "pip install -r requirements.txt"
    preDeployCommand: "flask db upgrade"
    startCommand: "python run.py"

  # --- SERVIÇO 2: A IA DO CHATBOT ---
 services:
  - type: web
    name: nicopel-chatbot-free
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --threads 2 --timeout 120 --bind 0.0.0.0:$PORT ia_server:app
    envVars:
      - key: key
        sync: false
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheck:
      path: /health
      interval: 30
      timeout: 10
      retries: 3
    plan: free
    instanceType: free
    region: oregon