services:
  - type: web
    name: sistema-chamados-nicopel
    env: python
    plan: free 
    region: oregon
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_APP
        value: run:app 
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DATABASE_URL
        fromDatabase:
          name: meubancochamados # SUBSTITUA pelo nome do seu DB na Render
          property: connectionString
      # Adicione suas chaves SECRET_KEY e GEMINI_API_KEY no painel da Render

    buildCommand: "pip install -r requirements.txt"
    preDeployCommand: "flask db upgrade"
    startCommand: "python run.py"