"""Adiciona coluna sistema_origem a tabela de chamados

Revision ID: 2a8badec35eb
Revises: 
Create Date: 2025-07-25 11:59:27.080104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a8badec35eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chamados', 'glpi_ticket_id')
    op.drop_column('chamados', 'anydesk')
    op.drop_column('usuario', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('role', sa.VARCHAR(length=20), server_default=sa.text("'user'"), nullable=False))
    op.add_column('chamados', sa.Column('anydesk', sa.VARCHAR(length=50), nullable=True))
    op.add_column('chamados', sa.Column('glpi_ticket_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
