"""Cria a estrutura inicial do banco de dados

Revision ID: 827047bbc3ad
Revises: 
Create Date: 2025-07-28 14:31:41.576780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827047bbc3ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('security_question', sa.String(length=50), nullable=True),
    sa.Column('security_answer', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('funcionario_id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)

    op.create_table('chamados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('setor', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('anydesk', sa.String(length=50), nullable=True),
    sa.Column('sistema_origem', sa.String(length=20), nullable=False),
    sa.Column('imagem_url', sa.String(length=200), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.Column('notificado', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('iniciado_em', sa.DateTime(), nullable=True),
    sa.Column('andamento_em', sa.DateTime(), nullable=True),
    sa.Column('concluido_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chamados_setor'), ['setor'], unique=False)
        batch_op.create_index(batch_op.f('ix_chamados_status'), ['status'], unique=False)

    op.create_table('historico_chamado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chamado_id', sa.Integer(), nullable=False),
    sa.Column('campo_alterado', sa.String(length=50), nullable=True),
    sa.Column('valor_anterior', sa.String(length=100), nullable=True),
    sa.Column('valor_novo', sa.String(length=100), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico_chamado')
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chamados_status'))
        batch_op.drop_index(batch_op.f('ix_chamados_setor'))

    op.drop_table('chamados')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_email'))

    op.drop_table('usuario')
    # ### end Alembic commands ###
