apiVersion: 1

datasources:
  - name: 'API Sistema de Chamados'
    type: 'simpod-json-datasource' # Nome do plugin Simple JSON
    url: 'http://host.docker.internal:5000/api/grafana' # URL para acessar sua API Flask local
    access: 'proxy'
    isDefault: true
    jsonData:
      timeInterval: "10s"